#!/usr/bin/env bash
set -euo pipefail

# Lab-wide Claude Code / Codex configuration installer
# Usage: ./setup.sh [--modules greatlakes,lighthouse] [--targets claude,codex] [--non-interactive]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="$HOME/.claude"
CODEX_DIR="$HOME/.codex"
BUILD_DIR="$SCRIPT_DIR/build"
BACKUP_DIR="$CLAUDE_DIR/backups/lab-config-backup"
CODEX_BACKUP_DIR="$CODEX_DIR/backups/lab-config-backup"
ENV_FILE="$BUILD_DIR/.env.local"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
ok()    { echo -e "${GREEN}[ OK ]${NC} $*"; }
err()   { echo -e "${RED}[ERR ]${NC} $*" >&2; }

# --- Parse arguments ---
MODULES=""
TARGETS="claude"
NON_INTERACTIVE=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --modules)
            MODULES="$2"
            shift 2
            ;;
        --targets)
            TARGETS="$2"
            shift 2
            ;;
        --codex)
            TARGETS="codex"
            shift
            ;;
        --both)
            TARGETS="claude,codex"
            shift
            ;;
        --non-interactive)
            NON_INTERACTIVE=true
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [--modules greatlakes,lighthouse|none] [--targets claude,codex] [--non-interactive]"
            echo ""
            echo "Options:"
            echo "  --modules           Comma-separated list of modules to enable (greatlakes,lighthouse,none)"
            echo "                      If not specified, auto-detects based on hostname"
            echo "  --targets           Comma-separated tools to configure (claude,codex). Default: claude"
            echo "  --codex             Shortcut for --targets codex"
            echo "  --both              Shortcut for --targets claude,codex"
            echo "  --non-interactive   Skip prompts, use saved values from .env.local or defaults"
            exit 0
            ;;
        *)
            err "Unknown argument: $1"
            exit 1
            ;;
    esac
done

# --- Auto-detect modules if not specified ---
if [[ -z "$MODULES" ]]; then
    info "Auto-detecting cluster modules..."
    MODULES=""

    # Great Lakes: check hostname pattern or sinfo for spgpu2
    if hostname -f 2>/dev/null | grep -qi "greatlakes\|gl-login" ||
       sinfo -p spgpu2 --noheader 2>/dev/null | grep -q "spgpu2"; then
        MODULES="greatlakes"
        info "Detected Great Lakes cluster"
    fi

    # Lighthouse: check hostname pattern or sinfo for lighthouse partitions
    if hostname -f 2>/dev/null | grep -qi "lighthouse\|lh-login" ||
       (sinfo -p gpu --noheader 2>/dev/null | grep -qi "a100" && ! hostname -f 2>/dev/null | grep -qi "greatlakes"); then
        if [[ -n "$MODULES" ]]; then
            MODULES="$MODULES,lighthouse"
        else
            MODULES="lighthouse"
        fi
        info "Detected Lighthouse cluster"
    fi

    if [[ -z "$MODULES" ]]; then
        warn "Could not auto-detect cluster. Use --modules to specify."
        MODULES="none"
    fi
fi

# Parse modules into array
IFS=',' read -ra MODULE_LIST <<< "$MODULES"
IFS=',' read -ra TARGET_LIST <<< "$TARGETS"

info "Modules to enable: ${MODULE_LIST[*]}"
info "Targets to configure: ${TARGET_LIST[*]}"

target_enabled() {
    local wanted="$1"
    for target in "${TARGET_LIST[@]}"; do
        [[ "$target" == "$wanted" ]] && return 0
    done
    return 1
}

for target in "${TARGET_LIST[@]}"; do
    case "$target" in
        claude|codex) ;;
        *)
            err "Unknown target: $target"
            exit 1
            ;;
    esac
done

# --- Check dependencies ---
if target_enabled claude && ! command -v python3 &>/dev/null; then
    err "python3 is required but not found. Load it with 'module load python' or install it."
    exit 1
fi
if target_enabled claude && ! command -v jq &>/dev/null; then
    err "jq is required (for the statusline) but not found. Load it with 'module load jq' or install it."
    exit 1
fi

# --- Ensure target config directories exist ---
if target_enabled claude && [[ ! -d "$CLAUDE_DIR" ]]; then
    err "~/.claude does not exist. Please run 'claude' at least once first."
    exit 1
fi
if target_enabled codex && [[ ! -d "$CODEX_DIR" ]]; then
    err "~/.codex does not exist. Please run 'codex' at least once first."
    exit 1
fi

# --- Load or create env file ---
mkdir -p "$BUILD_DIR"
declare -A ENV_VARS

load_env() {
    if [[ -f "$ENV_FILE" ]]; then
        while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" =~ ^# ]] && continue
            ENV_VARS["$key"]="$value"
        done < "$ENV_FILE"
    fi
}

save_env() {
    {
        echo "# Lab Claude Config - saved template variables"
        echo "# Generated by setup.sh - do not edit manually"
        for key in "${!ENV_VARS[@]}"; do
            echo "${key}=${ENV_VARS[$key]}"
        done
    } > "$ENV_FILE"
}

prompt_var() {
    local var_name="$1"
    local prompt_text="$2"
    local default="${3:-}"

    # Use saved value if available
    if [[ -n "${ENV_VARS[$var_name]:-}" ]]; then
        if [[ "$NON_INTERACTIVE" == true ]]; then
            return
        fi
        default="${ENV_VARS[$var_name]}"
    fi

    if [[ "$NON_INTERACTIVE" == true ]]; then
        if [[ -n "$default" ]]; then
            ENV_VARS["$var_name"]="$default"
        else
            err "Variable $var_name has no saved value and --non-interactive was specified"
            exit 1
        fi
        return
    fi

    local prompt_suffix=""
    if [[ -n "$default" ]]; then
        prompt_suffix=" [${default}]"
    fi

    read -rp "  ${prompt_text}${prompt_suffix}: " input
    ENV_VARS["$var_name"]="${input:-$default}"
}

load_env

# --- Prompt for module variables ---
for module in "${MODULE_LIST[@]}"; do
    case "$module" in
        greatlakes)
            info "Configuring Great Lakes module..."
            prompt_var "GL_USERNAME" "Slurm username" "$(whoami)"
            prompt_var "GL_ACCOUNT_OWNED" "Primary GPU account (owned, for spgpu2)" ""
            prompt_var "GL_ACCOUNT_GENERAL" "General account (for gpu, spgpu, etc.)" ""
            prompt_var "GL_MEMORY_CAP" "Group memory cap in GB" "620"
            ;;
        lighthouse)
            info "Configuring Lighthouse module..."
            prompt_var "LH_USERNAME" "Slurm username" "$(whoami)"
            prompt_var "LH_ACCOUNT" "GPU account" ""
            prompt_var "LH_PARTITION" "GPU partition name" "qmei-a100"
            prompt_var "LH_GPU_COUNT" "Group GPU allocation (total GPUs)" "4"
            prompt_var "LH_GPU_TYPE" "GPU type" "A100-SXM4-80GB"
            ;;
        none)
            info "No cluster modules selected."
            ;;
        *)
            err "Unknown module: $module"
            exit 1
            ;;
    esac
done

save_env

# --- Backup existing files ---
backup_if_exists() {
    local target="$1"
    local backup_dir="${2:-$BACKUP_DIR}"
    local backup_target="$target"

    if [[ -L "$target" ]]; then
        backup_target="$(readlink -f "$target")"
    fi

    if [[ -e "$backup_target" ]]; then
        mkdir -p "$backup_dir"
        local basename
        basename="$(basename "$backup_target")"
        cp -a "$backup_target" "$backup_dir/${basename}.$(date +%Y%m%d%H%M%S)"
        info "Backed up $backup_target"
    fi
}

if target_enabled claude; then
    backup_if_exists "$CLAUDE_DIR/settings.json"
    backup_if_exists "$CLAUDE_DIR/statusline-command.sh"
fi
if target_enabled codex; then
    backup_if_exists "$CODEX_DIR/AGENTS.md" "$CODEX_BACKUP_DIR"
fi

# --- Generate build/settings.json ---
if target_enabled claude; then
    info "Generating settings.json..."

    # Read shared settings and inject statusline with expanded $HOME
    SETTINGS_IN="$SCRIPT_DIR/shared/settings.json" \
    SETTINGS_OUT="$BUILD_DIR/settings.json" \
    SETTINGS_LOCAL="$CLAUDE_DIR/settings.local.json" \
    python3 -c "
import json, os, sys

def deep_merge(base, override):
    '''Recursively merge override into base. Arrays are concatenated with dedup.'''
    for key, val in override.items():
        if key in base and isinstance(base[key], dict) and isinstance(val, dict):
            deep_merge(base[key], val)
        elif key in base and isinstance(base[key], list) and isinstance(val, list):
            seen = set(json.dumps(x, sort_keys=True) if isinstance(x, (dict, list)) else x for x in base[key])
            for item in val:
                serialized = json.dumps(item, sort_keys=True) if isinstance(item, (dict, list)) else item
                if serialized not in seen:
                    base[key].append(item)
                    seen.add(serialized)
        else:
            base[key] = val
    return base

with open(os.environ['SETTINGS_IN']) as f:
    settings = json.load(f)
settings['statusLine'] = {
    'type': 'command',
    'command': f'bash {os.environ[\"HOME\"]}/.claude/statusline-command.sh'
}
settings['hooks'] = {
    'PreToolUse': [
        {
            'matcher': 'Bash',
            'hooks': [
                {
                    'type': 'command',
                    'command': f'bash {os.environ[\"HOME\"]}/.claude/hooks/node-context.sh'
                }
            ]
        }
    ],
    'PostToolUse': [
        {
            'matcher': 'Edit',
            'hooks': [{'type': 'command', 'command': 'case \"\$CLAUDE_FILE_PATH\" in *.py) ruff check --fix \"\$CLAUDE_FILE_PATH\" ;; esac'}]
        },
        {
            'matcher': 'Write',
            'hooks': [{'type': 'command', 'command': 'case \"\$CLAUDE_FILE_PATH\" in *.py) ruff check --fix \"\$CLAUDE_FILE_PATH\" ;; esac'}]
        },
        {
            'matcher': 'Edit',
            'hooks': [{'type': 'command', 'command': 'case \"\$CLAUDE_FILE_PATH\" in */submit*.sh) bash -n \"\$CLAUDE_FILE_PATH\" && echo \"SLURM script syntax OK\" ;; esac'}]
        },
        {
            'matcher': 'Write',
            'hooks': [{'type': 'command', 'command': 'case \"\$CLAUDE_FILE_PATH\" in */submit*.sh) bash -n \"\$CLAUDE_FILE_PATH\" && echo \"SLURM script syntax OK\" ;; esac'}]
        }
    ]
}

# Merge user's local overrides if they exist
local_path = os.environ['SETTINGS_LOCAL']
if os.path.isfile(local_path):
    try:
        with open(local_path) as f:
            overrides = json.load(f)
        deep_merge(settings, overrides)
    except json.JSONDecodeError as e:
        print(f'Error: {local_path} contains invalid JSON: {e}', file=sys.stderr)
        sys.exit(1)

with open(os.environ['SETTINGS_OUT'], 'w') as f:
    json.dump(settings, f, indent=2)
    f.write('\n')
"
    ok "Generated build/settings.json"
fi

# --- Inject lab config into ~/.claude/CLAUDE.md ---
BEGIN_MARKER="<!-- BEGIN: lab-config -->"
END_MARKER="<!-- END: lab-config -->"

expand_vars() {
    local content="$1"
    for key in "${!ENV_VARS[@]}"; do
        content="${content//\{\{$key\}\}/${ENV_VARS[$key]}}"
    done
    echo "$content"
}

build_doc_block() {
    local target="$1"

    local block="$BEGIN_MARKER"

    if [[ -f "$SCRIPT_DIR/shared/instructions/core.md" ]]; then
        block="$block
$(cat "$SCRIPT_DIR/shared/instructions/core.md")"
    fi

    if [[ -f "$SCRIPT_DIR/shared/instructions/$target.md" ]]; then
        block="$block

$(cat "$SCRIPT_DIR/shared/instructions/$target.md")"
    fi

    for module in "${MODULE_LIST[@]}"; do
        [[ "$module" == "none" ]] && continue

        if [[ -f "$SCRIPT_DIR/modules/$module/instructions/core.md" ]]; then
            block="$block

$(cat "$SCRIPT_DIR/modules/$module/instructions/core.md")"
        fi

        if [[ -f "$SCRIPT_DIR/modules/$module/instructions/$target.md" ]]; then
            block="$block

$(cat "$SCRIPT_DIR/modules/$module/instructions/$target.md")"
        fi
    done

    block="$block
$END_MARKER"

    expand_vars "$block"
}

inject_marked_block() {
    local target_file="$1"
    local block="$2"
    local doc_label="$3"
    local write_file="$target_file"

    if [[ -L "$target_file" ]]; then
        write_file="$(readlink -f "$target_file")"
    fi

    if [[ ! -f "$write_file" ]]; then
        echo "$block" > "$write_file"
        ok "Created $doc_label with lab config"
    elif grep -qF "$BEGIN_MARKER" "$write_file"; then
        awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v block="$block" '
            $0 == begin { print block; skip=1; next }
            $0 == end   { skip=0; next }
            !skip       { print }
        ' "$write_file" > "$write_file.tmp"
        mv "$write_file.tmp" "$write_file"
        ok "Updated lab config block in $doc_label"
    else
        {
            echo "$block"
            echo ""
            cat "$write_file"
        } > "$write_file.tmp"
        mv "$write_file.tmp" "$write_file"
        ok "Prepended lab config block to existing $doc_label"
    fi
}

if target_enabled claude; then
    info "Injecting lab config into CLAUDE.md..."
    CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"
    inject_marked_block "$CLAUDE_MD" "$(build_doc_block claude)" "CLAUDE.md"
fi

if target_enabled codex; then
    info "Injecting lab config into AGENTS.md..."
    CODEX_AGENTS_MD="$CODEX_DIR/AGENTS.md"
    inject_marked_block "$CODEX_AGENTS_MD" "$(build_doc_block codex)" "AGENTS.md"
fi

# --- Generate skill files from templates ---
expand_template() {
    local template="$1"
    local output="$2"

    mkdir -p "$(dirname "$output")"

    local content
    content="$(cat "$template")"

    # Replace all {{VAR}} placeholders with values from ENV_VARS
    for key in "${!ENV_VARS[@]}"; do
        content="${content//\{\{$key\}\}/${ENV_VARS[$key]}}"
    done

    echo "$content" > "$output"
}

# Clear Codex-generated agent skill outputs when configuring Codex so stale
# generated files cannot survive a setup run.
if target_enabled codex; then
    rm -rf "$BUILD_DIR/codex/skills"
fi

# Determine which slurm-status template to use.
# If both greatlakes and lighthouse are active, use the combined template.
_has_gl=false
_has_lh=false
SLURM_STATUS_GENERATED=false
for module in "${MODULE_LIST[@]}"; do
    [[ "$module" == "greatlakes" ]] && _has_gl=true
    [[ "$module" == "lighthouse" ]] && _has_lh=true
done

if $_has_gl && $_has_lh; then
    if [[ -f "$SCRIPT_DIR/modules/combined/skills/slurm-status/SKILL.md.template" ]]; then
        info "Generating combined slurm-status skill (Great Lakes + Lighthouse)..."
        mkdir -p "$BUILD_DIR/skills/slurm-status"
        expand_template \
            "$SCRIPT_DIR/modules/combined/skills/slurm-status/SKILL.md.template" \
            "$BUILD_DIR/skills/slurm-status/SKILL.md"
        SLURM_STATUS_GENERATED=true
        ok "Generated combined slurm-status skill"
    fi
elif $_has_gl; then
    if [[ -f "$SCRIPT_DIR/modules/greatlakes/skills/slurm-status/SKILL.md.template" ]]; then
        info "Generating slurm-status skill (Great Lakes)..."
        mkdir -p "$BUILD_DIR/skills/slurm-status"
        expand_template \
            "$SCRIPT_DIR/modules/greatlakes/skills/slurm-status/SKILL.md.template" \
            "$BUILD_DIR/skills/slurm-status/SKILL.md"
        SLURM_STATUS_GENERATED=true
        ok "Generated slurm-status skill"
    fi
elif $_has_lh; then
    if [[ -f "$SCRIPT_DIR/modules/lighthouse/skills/slurm-status/SKILL.md.template" ]]; then
        info "Generating slurm-status skill (Lighthouse)..."
        mkdir -p "$BUILD_DIR/skills/slurm-status"
        expand_template \
            "$SCRIPT_DIR/modules/lighthouse/skills/slurm-status/SKILL.md.template" \
            "$BUILD_DIR/skills/slurm-status/SKILL.md"
        SLURM_STATUS_GENERATED=true
        ok "Generated slurm-status skill"
    fi
fi

# --- Create symlinks ---
create_symlink() {
    local source="$1"
    local target="$2"
    local backup_dir="$BACKUP_DIR"

    if [[ "$target" == "$CODEX_DIR/"* ]]; then
        backup_dir="$CODEX_BACKUP_DIR"
    fi

    if [[ -L "$target" ]]; then
        rm "$target"
    elif [[ -e "$target" ]]; then
        backup_if_exists "$target" "$backup_dir"
        rm -rf "$target"
    fi

    mkdir -p "$(dirname "$target")"
    ln -s "$source" "$target"
    ok "Linked $target -> $source"
}

remove_repo_symlink_if_present() {
    local target="$1"
    if [[ -L "$target" ]]; then
        local link_dest
        link_dest="$(readlink -f "$target" 2>/dev/null || true)"
        if [[ ! -e "$target" || "$link_dest" == "$SCRIPT_DIR/"* ]]; then
            rm "$target"
            ok "Removed stale symlink: $target"
        fi
    fi
}

if target_enabled claude; then
    create_symlink "$BUILD_DIR/settings.json" "$CLAUDE_DIR/settings.json"
    create_symlink "$SCRIPT_DIR/shared/statusline-command.sh" "$CLAUDE_DIR/statusline-command.sh"

    # Symlink generated skill directories (e.g. slurm-status)
    if [[ "$SLURM_STATUS_GENERATED" == true ]]; then
        create_symlink "$BUILD_DIR/skills/slurm-status" "$CLAUDE_DIR/skills/slurm-status"
    else
        remove_repo_symlink_if_present "$CLAUDE_DIR/skills/slurm-status"
    fi

    # Symlink shared hook files (individual files, not the whole directory,
    # to preserve any user-created hooks already in ~/.claude/hooks/)
    if [[ -d "$SCRIPT_DIR/shared/hooks" ]]; then
        # Remove old directory-level symlink from previous setup versions
        if [[ -L "$CLAUDE_DIR/hooks" ]]; then
            rm "$CLAUDE_DIR/hooks"
        fi
        mkdir -p "$CLAUDE_DIR/hooks"
        for hook_file in "$SCRIPT_DIR/shared/hooks"/*; do
            if [[ -f "$hook_file" ]]; then
                hook_name="$(basename "$hook_file")"
                create_symlink "$hook_file" "$CLAUDE_DIR/hooks/$hook_name"
            fi
        done
    fi

    # Symlink shared skills directory contents
    if [[ -d "$SCRIPT_DIR/shared/skills" ]]; then
        for skill_dir in "$SCRIPT_DIR/shared/skills"/*/; do
            if [[ -d "$skill_dir" ]]; then
                skill_name="$(basename "$skill_dir")"
                create_symlink "$skill_dir" "$CLAUDE_DIR/skills/$skill_name"
            fi
        done
    fi

    # Symlink shared agents
    if [[ -d "$SCRIPT_DIR/shared/agents" ]]; then
        for agent_file in "$SCRIPT_DIR/shared/agents"/*.md; do
            if [[ -f "$agent_file" ]]; then
                agent_name="$(basename "$agent_file")"
                create_symlink "$agent_file" "$CLAUDE_DIR/agents/$agent_name"
            fi
        done
    fi
fi

if target_enabled codex; then
    declare -A CODEX_SKILL_OVERRIDES=()

    if [[ -d "$SCRIPT_DIR/shared/codex/skills" ]]; then
        for skill_dir in "$SCRIPT_DIR/shared/codex/skills"/*/; do
            if [[ -d "$skill_dir" ]]; then
                skill_name="$(basename "$skill_dir")"
                CODEX_SKILL_OVERRIDES["$skill_name"]=1
                create_symlink "$skill_dir" "$CODEX_DIR/skills/$skill_name"
            fi
        done
    fi

    if [[ "$SLURM_STATUS_GENERATED" == true ]]; then
        create_symlink "$BUILD_DIR/skills/slurm-status" "$CODEX_DIR/skills/slurm-status"
        CODEX_SKILL_OVERRIDES["slurm-status"]=1
    else
        remove_repo_symlink_if_present "$CODEX_DIR/skills/slurm-status"
    fi

    if [[ -d "$SCRIPT_DIR/shared/skills" ]]; then
        for skill_dir in "$SCRIPT_DIR/shared/skills"/*/; do
            if [[ -d "$skill_dir" ]]; then
                skill_name="$(basename "$skill_dir")"
                if [[ -z "${CODEX_SKILL_OVERRIDES[$skill_name]:-}" ]]; then
                    create_symlink "$skill_dir" "$CODEX_DIR/skills/$skill_name"
                fi
            fi
        done
    fi

    if [[ -d "$SCRIPT_DIR/shared/agents" ]]; then
        for agent_file in "$SCRIPT_DIR/shared/agents"/*.md; do
            if [[ -f "$agent_file" ]]; then
                agent_name="$(basename "$agent_file" .md)"
                mkdir -p "$BUILD_DIR/codex/skills/$agent_name"
                cp "$agent_file" "$BUILD_DIR/codex/skills/$agent_name/SKILL.md"
                create_symlink "$BUILD_DIR/codex/skills/$agent_name" "$CODEX_DIR/skills/$agent_name"
            fi
        done
    fi
fi

# --- Summary ---
echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN} Lab AI coding config installed successfully!${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo "  Modules enabled: ${MODULE_LIST[*]}"
echo "  Targets enabled: ${TARGET_LIST[*]}"
echo "  Config repo:     $SCRIPT_DIR"
echo "  Build dir:       $BUILD_DIR"
echo ""
if target_enabled claude; then
    echo "  Claude symlinks created:"
    echo "    ~/.claude/settings.json         -> build/settings.json"
    echo "    ~/.claude/statusline-command.sh -> shared/statusline-command.sh"
    if [[ "$SLURM_STATUS_GENERATED" == true ]]; then
        echo "    ~/.claude/skills/slurm-status   -> build/skills/slurm-status"
    fi
    if [[ -d "$SCRIPT_DIR/shared/hooks" ]]; then
        for hook_file in "$SCRIPT_DIR/shared/hooks"/*; do
            if [[ -f "$hook_file" ]]; then
                hook_name="$(basename "$hook_file")"
                echo "    ~/.claude/hooks/$hook_name -> shared/hooks/$hook_name"
            fi
        done
    fi
    if [[ -d "$SCRIPT_DIR/shared/skills" ]]; then
        for skill_dir in "$SCRIPT_DIR/shared/skills"/*/; do
            if [[ -d "$skill_dir" ]]; then
                skill_name="$(basename "$skill_dir")"
                echo "    ~/.claude/skills/$skill_name -> shared/skills/$skill_name"
            fi
        done
    fi
    if [[ -d "$SCRIPT_DIR/shared/agents" ]]; then
        for agent_file in "$SCRIPT_DIR/shared/agents"/*.md; do
            if [[ -f "$agent_file" ]]; then
                agent_name="$(basename "$agent_file")"
                echo "    ~/.claude/agents/$agent_name -> shared/agents/$agent_name"
            fi
        done
    fi
    echo ""
    echo "  CLAUDE.md: lab config injected between markers"
    echo "    Edit freely outside the <!-- BEGIN/END: lab-config --> markers."
fi

if target_enabled codex; then
    echo "  Codex symlinks created:"
    if [[ "$SLURM_STATUS_GENERATED" == true ]]; then
        echo "    ~/.codex/skills/slurm-status    -> build/skills/slurm-status"
    fi
    if [[ -d "$SCRIPT_DIR/shared/skills" ]]; then
        for skill_dir in "$SCRIPT_DIR/shared/skills"/*/; do
            if [[ -d "$skill_dir" ]]; then
                skill_name="$(basename "$skill_dir")"
                [[ -n "${CODEX_SKILL_OVERRIDES[$skill_name]:-}" ]] && continue
                echo "    ~/.codex/skills/$skill_name -> shared/skills/$skill_name"
            fi
        done
    fi
    if [[ -d "$SCRIPT_DIR/shared/codex/skills" ]]; then
        for skill_dir in "$SCRIPT_DIR/shared/codex/skills"/*/; do
            if [[ -d "$skill_dir" ]]; then
                skill_name="$(basename "$skill_dir")"
                echo "    ~/.codex/skills/$skill_name -> shared/codex/skills/$skill_name"
            fi
        done
    fi
    if [[ -d "$SCRIPT_DIR/shared/agents" ]]; then
        for agent_file in "$SCRIPT_DIR/shared/agents"/*.md; do
            if [[ -f "$agent_file" ]]; then
                agent_name="$(basename "$agent_file" .md)"
                echo "    ~/.codex/skills/$agent_name -> build/codex/skills/$agent_name"
            fi
        done
    fi
    echo ""
    echo "  AGENTS.md: lab config injected between markers"
    echo "    Edit freely outside the <!-- BEGIN/END: lab-config --> markers."
fi
echo ""
echo "  To customize:"
if target_enabled claude; then
    echo "    - Claude: edit ~/.claude/settings.local.json for extra permissions, then re-run: ./setup.sh"
    echo "    - Claude: edit ~/.claude/CLAUDE.md - your content outside the markers is preserved"
fi
if target_enabled codex; then
    echo "    - Codex: edit ~/.codex/AGENTS.md - your content outside the markers is preserved"
fi
echo "    - Re-run ./setup.sh after git pull to pick up shared changes"
echo ""
