#!/usr/bin/env bash
set -euo pipefail

# Lab-wide Claude Code configuration installer
# Usage: ./setup.sh [--modules greatlakes,lighthouse] [--non-interactive]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="$HOME/.claude"
BUILD_DIR="$SCRIPT_DIR/build"
BACKUP_DIR="$CLAUDE_DIR/backups/lab-config-backup"
ENV_FILE="$BUILD_DIR/.env.local"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
ok()    { echo -e "${GREEN}[ OK ]${NC} $*"; }
err()   { echo -e "${RED}[ERR ]${NC} $*" >&2; }

# --- Parse arguments ---
MODULES=""
NON_INTERACTIVE=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --modules)
            MODULES="$2"
            shift 2
            ;;
        --non-interactive)
            NON_INTERACTIVE=true
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [--modules greatlakes,lighthouse|none] [--non-interactive]"
            echo ""
            echo "Options:"
            echo "  --modules           Comma-separated list of modules to enable (greatlakes,lighthouse,none)"
            echo "                      If not specified, auto-detects based on hostname"
            echo "  --non-interactive   Skip prompts, use saved values from .env.local or defaults"
            exit 0
            ;;
        *)
            err "Unknown argument: $1"
            exit 1
            ;;
    esac
done

# --- Auto-detect modules if not specified ---
if [[ -z "$MODULES" ]]; then
    info "Auto-detecting cluster modules..."
    MODULES=""

    # Great Lakes: check hostname pattern or sinfo for spgpu2
    if hostname -f 2>/dev/null | grep -qi "greatlakes\|gl-login" ||
       sinfo -p spgpu2 --noheader 2>/dev/null | grep -q "spgpu2"; then
        MODULES="greatlakes"
        info "Detected Great Lakes cluster"
    fi

    # Lighthouse: check hostname pattern or sinfo for lighthouse partitions
    if hostname -f 2>/dev/null | grep -qi "lighthouse\|lh-login" ||
       (sinfo -p gpu --noheader 2>/dev/null | grep -qi "a100" && ! hostname -f 2>/dev/null | grep -qi "greatlakes"); then
        if [[ -n "$MODULES" ]]; then
            MODULES="$MODULES,lighthouse"
        else
            MODULES="lighthouse"
        fi
        info "Detected Lighthouse cluster"
    fi

    if [[ -z "$MODULES" ]]; then
        warn "Could not auto-detect cluster. Use --modules to specify."
        MODULES="none"
    fi
fi

# Parse modules into array
IFS=',' read -ra MODULE_LIST <<< "$MODULES"

info "Modules to enable: ${MODULE_LIST[*]}"

# --- Check dependencies ---
if ! command -v python3 &>/dev/null; then
    err "python3 is required but not found. Load it with 'module load python' or install it."
    exit 1
fi
if ! command -v jq &>/dev/null; then
    err "jq is required (for the statusline) but not found. Load it with 'module load jq' or install it."
    exit 1
fi

# --- Ensure ~/.claude exists ---
if [[ ! -d "$CLAUDE_DIR" ]]; then
    err "~/.claude does not exist. Please run 'claude' at least once first."
    exit 1
fi

# --- Load or create env file ---
mkdir -p "$BUILD_DIR"
declare -A ENV_VARS

load_env() {
    if [[ -f "$ENV_FILE" ]]; then
        while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" =~ ^# ]] && continue
            ENV_VARS["$key"]="$value"
        done < "$ENV_FILE"
    fi
}

save_env() {
    {
        echo "# Lab Claude Config - saved template variables"
        echo "# Generated by setup.sh - do not edit manually"
        for key in "${!ENV_VARS[@]}"; do
            echo "${key}=${ENV_VARS[$key]}"
        done
    } > "$ENV_FILE"
}

prompt_var() {
    local var_name="$1"
    local prompt_text="$2"
    local default="${3:-}"

    # Use saved value if available
    if [[ -n "${ENV_VARS[$var_name]:-}" ]]; then
        if [[ "$NON_INTERACTIVE" == true ]]; then
            return
        fi
        default="${ENV_VARS[$var_name]}"
    fi

    if [[ "$NON_INTERACTIVE" == true ]]; then
        if [[ -n "$default" ]]; then
            ENV_VARS["$var_name"]="$default"
        else
            err "Variable $var_name has no saved value and --non-interactive was specified"
            exit 1
        fi
        return
    fi

    local prompt_suffix=""
    if [[ -n "$default" ]]; then
        prompt_suffix=" [${default}]"
    fi

    read -rp "  ${prompt_text}${prompt_suffix}: " input
    ENV_VARS["$var_name"]="${input:-$default}"
}

load_env

# --- Prompt for module variables ---
for module in "${MODULE_LIST[@]}"; do
    case "$module" in
        greatlakes)
            info "Configuring Great Lakes module..."
            prompt_var "GL_USERNAME" "Slurm username" "$(whoami)"
            prompt_var "GL_ACCOUNT_OWNED" "Primary GPU account (owned, for spgpu2)" ""
            prompt_var "GL_ACCOUNT_GENERAL" "General account (for gpu, spgpu, etc.)" ""
            prompt_var "GL_MEMORY_CAP" "Group memory cap in GB" "620"
            ;;
        lighthouse)
            info "Configuring Lighthouse module..."
            prompt_var "LH_USERNAME" "Slurm username" "$(whoami)"
            prompt_var "LH_ACCOUNT" "GPU account" ""
            prompt_var "LH_GPU_COUNT" "Group GPU allocation (total GPUs)" "4"
            prompt_var "LH_GPU_TYPE" "GPU type" "A100 80GB"
            ;;
        none)
            info "No cluster modules selected."
            ;;
        *)
            err "Unknown module: $module"
            exit 1
            ;;
    esac
done

save_env

# --- Backup existing files ---
backup_if_exists() {
    local target="$1"
    if [[ -e "$target" && ! -L "$target" ]]; then
        mkdir -p "$BACKUP_DIR"
        local basename
        basename="$(basename "$target")"
        cp -a "$target" "$BACKUP_DIR/${basename}.$(date +%Y%m%d%H%M%S)"
        info "Backed up $target"
    fi
}

backup_if_exists "$CLAUDE_DIR/settings.json"
backup_if_exists "$CLAUDE_DIR/statusline-command.sh"

# --- Generate build/settings.json ---
info "Generating settings.json..."

# Read shared settings and inject statusline with expanded $HOME
SETTINGS_IN="$SCRIPT_DIR/shared/settings.json" \
SETTINGS_OUT="$BUILD_DIR/settings.json" \
python3 -c "
import json, os
with open(os.environ['SETTINGS_IN']) as f:
    settings = json.load(f)
settings['statusLine'] = {
    'type': 'command',
    'command': f'bash {os.environ[\"HOME\"]}/.claude/statusline-command.sh'
}
settings['hooks'] = {
    'PreToolUse': [
        {
            'matcher': 'Bash',
            'hooks': [
                {
                    'type': 'command',
                    'command': f'bash {os.environ[\"HOME\"]}/.claude/hooks/node-context.sh'
                }
            ]
        }
    ]
}
with open(os.environ['SETTINGS_OUT'], 'w') as f:
    json.dump(settings, f, indent=2)
    f.write('\n')
"
ok "Generated build/settings.json"

# --- Inject lab config into ~/.claude/CLAUDE.md ---
CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"
BEGIN_MARKER="<!-- BEGIN: lab-config -->"
END_MARKER="<!-- END: lab-config -->"

info "Injecting lab config into CLAUDE.md..."

# Build the lab config block
lab_block="$BEGIN_MARKER
$(cat "$SCRIPT_DIR/shared/CLAUDE.md")
$(
    for module in "${MODULE_LIST[@]}"; do
        if [[ "$module" != "none" && -f "$SCRIPT_DIR/modules/$module/CLAUDE.md" ]]; then
            echo ""
            cat "$SCRIPT_DIR/modules/$module/CLAUDE.md"
        fi
    done
)
$END_MARKER"

# Expand {{VAR}} placeholders in lab_block with saved template variables
for key in "${!ENV_VARS[@]}"; do
    lab_block="${lab_block//\{\{$key\}\}/${ENV_VARS[$key]}}"
done

if [[ ! -f "$CLAUDE_MD" ]]; then
    # No existing CLAUDE.md — create one with just the lab block
    echo "$lab_block" > "$CLAUDE_MD"
    ok "Created CLAUDE.md with lab config"
elif grep -qF "$BEGIN_MARKER" "$CLAUDE_MD"; then
    # Markers exist — replace content between them
    # Use awk to replace everything between BEGIN and END markers (inclusive)
    awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v block="$lab_block" '
        $0 == begin { print block; skip=1; next }
        $0 == end   { skip=0; next }
        !skip       { print }
    ' "$CLAUDE_MD" > "$CLAUDE_MD.tmp"
    mv "$CLAUDE_MD.tmp" "$CLAUDE_MD"
    ok "Updated lab config block in CLAUDE.md"
else
    # No markers — prepend lab block to existing content
    {
        echo "$lab_block"
        echo ""
        cat "$CLAUDE_MD"
    } > "$CLAUDE_MD.tmp"
    mv "$CLAUDE_MD.tmp" "$CLAUDE_MD"
    ok "Prepended lab config block to existing CLAUDE.md"
fi

# --- Generate skill files from templates ---
expand_template() {
    local template="$1"
    local output="$2"

    mkdir -p "$(dirname "$output")"

    local content
    content="$(cat "$template")"

    # Replace all {{VAR}} placeholders with values from ENV_VARS
    for key in "${!ENV_VARS[@]}"; do
        content="${content//\{\{$key\}\}/${ENV_VARS[$key]}}"
    done

    echo "$content" > "$output"
}

for module in "${MODULE_LIST[@]}"; do
    case "$module" in
        greatlakes)
            if [[ -f "$SCRIPT_DIR/modules/greatlakes/skills/slurm-status/SKILL.md.template" ]]; then
                info "Generating slurm-status skill..."
                mkdir -p "$BUILD_DIR/skills/slurm-status"
                expand_template \
                    "$SCRIPT_DIR/modules/greatlakes/skills/slurm-status/SKILL.md.template" \
                    "$BUILD_DIR/skills/slurm-status/SKILL.md"
                ok "Generated slurm-status skill"
            fi
            ;;
        lighthouse)
            if [[ -f "$SCRIPT_DIR/modules/lighthouse/skills/slurm-status/SKILL.md.template" ]]; then
                info "Generating slurm-status skill..."
                mkdir -p "$BUILD_DIR/skills/slurm-status"
                expand_template \
                    "$SCRIPT_DIR/modules/lighthouse/skills/slurm-status/SKILL.md.template" \
                    "$BUILD_DIR/skills/slurm-status/SKILL.md"
                ok "Generated slurm-status skill"
            fi
            ;;
    esac
done

# --- Create symlinks ---
create_symlink() {
    local source="$1"
    local target="$2"

    if [[ -L "$target" ]]; then
        rm "$target"
    elif [[ -e "$target" ]]; then
        backup_if_exists "$target"
        rm -f "$target"
    fi

    mkdir -p "$(dirname "$target")"
    ln -s "$source" "$target"
    ok "Linked $target -> $source"
}

create_symlink "$BUILD_DIR/settings.json" "$CLAUDE_DIR/settings.json"
create_symlink "$SCRIPT_DIR/shared/statusline-command.sh" "$CLAUDE_DIR/statusline-command.sh"

# Symlink skill directories
for module in "${MODULE_LIST[@]}"; do
    case "$module" in
        greatlakes)
            if [[ -d "$BUILD_DIR/skills/slurm-status" ]]; then
                create_symlink "$BUILD_DIR/skills/slurm-status" "$CLAUDE_DIR/skills/slurm-status"
            fi
            ;;
        lighthouse)
            if [[ -d "$BUILD_DIR/skills/slurm-status" ]]; then
                create_symlink "$BUILD_DIR/skills/slurm-status" "$CLAUDE_DIR/skills/slurm-status"
            fi
            ;;
    esac
done

# Symlink shared hooks directory
if [[ -d "$SCRIPT_DIR/shared/hooks" ]]; then
    create_symlink "$SCRIPT_DIR/shared/hooks" "$CLAUDE_DIR/hooks"
fi

# Symlink shared skills directory contents
if [[ -d "$SCRIPT_DIR/shared/skills" ]]; then
    for skill_dir in "$SCRIPT_DIR/shared/skills"/*/; do
        if [[ -d "$skill_dir" ]]; then
            skill_name="$(basename "$skill_dir")"
            create_symlink "$skill_dir" "$CLAUDE_DIR/skills/$skill_name"
        fi
    done
fi

# Symlink shared agents
if [[ -d "$SCRIPT_DIR/shared/agents" ]]; then
    for agent_file in "$SCRIPT_DIR/shared/agents"/*.md; do
        if [[ -f "$agent_file" ]]; then
            agent_name="$(basename "$agent_file")"
            create_symlink "$agent_file" "$CLAUDE_DIR/agents/$agent_name"
        fi
    done
fi

# --- Copy settings.local.json.example if needed ---
if [[ ! -f "$CLAUDE_DIR/settings.local.json" ]]; then
    cp "$SCRIPT_DIR/templates/settings.local.json.example" "$CLAUDE_DIR/settings.local.json"
    ok "Created settings.local.json from template (edit to customize permissions)"
fi

# --- Summary ---
echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN} Lab Claude Config installed successfully!${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo "  Modules enabled: ${MODULE_LIST[*]}"
echo "  Config repo:     $SCRIPT_DIR"
echo "  Build dir:       $BUILD_DIR"
echo ""
echo "  Symlinks created:"
echo "    ~/.claude/settings.json        -> build/settings.json"
echo "    ~/.claude/statusline-command.sh -> shared/statusline-command.sh"
if [[ -d "$BUILD_DIR/skills/slurm-status" ]]; then
    echo "    ~/.claude/skills/slurm-status  -> build/skills/slurm-status"
fi
if [[ -d "$SCRIPT_DIR/shared/hooks" ]]; then
    echo "    ~/.claude/hooks               -> shared/hooks"
fi
if [[ -d "$SCRIPT_DIR/shared/skills" ]]; then
    for skill_dir in "$SCRIPT_DIR/shared/skills"/*/; do
        if [[ -d "$skill_dir" ]]; then
            skill_name="$(basename "$skill_dir")"
            echo "    ~/.claude/skills/$skill_name -> shared/skills/$skill_name"
        fi
    done
fi
if [[ -d "$SCRIPT_DIR/shared/agents" ]]; then
    for agent_file in "$SCRIPT_DIR/shared/agents"/*.md; do
        if [[ -f "$agent_file" ]]; then
            agent_name="$(basename "$agent_file")"
            echo "    ~/.claude/agents/$agent_name -> shared/agents/$agent_name"
        fi
    done
fi
echo ""
echo "  CLAUDE.md: lab config injected between markers"
echo "    Edit freely outside the <!-- BEGIN/END: lab-config --> markers."
echo ""
echo "  To customize:"
echo "    - Edit ~/.claude/settings.local.json for personal permissions"
echo "    - Edit ~/.claude/CLAUDE.md — your content outside the markers is preserved"
echo "    - Re-run ./setup.sh after git pull to pick up shared changes"
echo ""
